/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import generalAccessPackage.classSubSystem.Address;
import generalAccessPackage.classSubSystem.GetMeADate;
import generalAccessPackage.classSubSystem.Person;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Diego Simões Maria, Italo Gustavo Donato Cordeiro, Marina Bernardes Diniz, Matheus Thiago de Souza Ferreira e Rosane Silva Freitas Araujo
 */
public class UserInterface extends javax.swing.JFrame {

    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
        this.dates = new GetMeADate();
        initListas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proximidadeGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Get Me A Date");
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados Pessoais"));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Id:");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setToolTipText("Identificação do usuário, só modifique se for buscar um usuário existente");

        jButton2.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jButton2.setText("Pesquisar");
        jButton2.setToolTipText("Procurar informações do ID no banco de dados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Nome:");

        jTextField2.setToolTipText("Digite o nome completo");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Idade:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Sexualidade:");

        jComboBox1.setToolTipText("Selecione o sexo com que você se identifica");

        jComboBox7.setToolTipText("Selecione a opção em que sua idade se enquadra");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Telefone:");

        jTextField4.setToolTipText("Digite o numero com o DD, ex: (XX) X XXXX-XXXX ");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Interesse:");

        jComboBox2.setToolTipText("Selecione o sexo que procura");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Escolaridade:");

        jComboBox3.setToolTipText("Selecione seu nivel de ecolaridade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(164, 164, 164)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Localização"));
        jPanel3.setMaximumSize(new java.awt.Dimension(1280, 720));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Cidade:");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Estado:");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("País:");

        jComboBox4.setToolTipText("Selecione o país que você reside");
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paiseesComboBoxActionPerformed(evt);
            }
        });

        jComboBox5.setToolTipText("Selecione o estado que você reside");
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadosComboBoxActionPerformed(evt);
            }
        });

        jComboBox6.setToolTipText("Selecione a cidade que você reside");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("Proximidade:");

        proximidadeGroup.add(jRadioButton1);
        jRadioButton1.setText("Mesma Cidade");
        jRadioButton1.setToolTipText("Selecione o raio de alcance de pesquisa");

        proximidadeGroup.add(jRadioButton2);
        jRadioButton2.setText("Mesmo Estado");
        jRadioButton2.setToolTipText("Selecione o raio de alcance de pesquisa");

        proximidadeGroup.add(jRadioButton3);
        jRadioButton3.setText("Mesmo País");
        jRadioButton3.setToolTipText("Selecione o raio de alcance de pesquisa");

        proximidadeGroup.add(jRadioButton4);
        jRadioButton4.setText("Qualquer Lugar");
        jRadioButton4.setToolTipText("Selecione o raio de alcance de pesquisa");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox4, 0, 96, Short.MAX_VALUE)
                            .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jRadioButton4))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(14, 14, 14))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Hobbies"));
        jPanel2.setToolTipText("Selecione os itens de interesse");
        jPanel2.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel2.setPreferredSize(new java.awt.Dimension(565, 135));

        jCheckBox1.setText("Musica");

        jCheckBox2.setText("Séries");

        jCheckBox3.setText("Filmes");

        jCheckBox4.setText("Festas");

        jCheckBox5.setText("Escrita");

        jCheckBox6.setText("Leitura");

        jCheckBox7.setText("Esportes");

        jCheckBox8.setText("Games");

        jCheckBox9.setText("Dança");

        jCheckBox10.setText("Teatro");

        jCheckBox11.setText("Shows");

        jCheckBox12.setText("Natureza");

        jCheckBox13.setText("Automobilismo");

        jCheckBox14.setText("Piadas");

        jCheckBox15.setText("Bar");

        jCheckBox16.setText("Estudar");

        jCheckBox17.setText("Desenhos");

        jCheckBox18.setText("Trabalhar");

        jCheckBox19.setText("Amizade");

        jCheckBox20.setText("Bate Papo");

        jCheckBox21.setText("Namoro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBox14)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCheckBox19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox21))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox7)
                                    .addComponent(jCheckBox1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jCheckBox9))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jCheckBox16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox17))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jCheckBox10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox11)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox12)
                                    .addComponent(jCheckBox18)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jCheckBox6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox8)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox13)))))
                .addGap(7, 7, 7))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox10)
                    .addComponent(jCheckBox11)
                    .addComponent(jCheckBox12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox14)
                    .addComponent(jCheckBox15)
                    .addComponent(jCheckBox16)
                    .addComponent(jCheckBox17)
                    .addComponent(jCheckBox18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox19)
                    .addComponent(jCheckBox20)
                    .addComponent(jCheckBox21)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox13))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Perfis Compativeis"));
        jPanel4.setMaximumSize(new java.awt.Dimension(1280, 720));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Buscar");
        jButton1.setToolTipText("Buscar perfis compativeis");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(494, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );

        jButton3.setText("Inserir");
        jButton3.setToolTipText("Cadastrar perfil no banco de dados");
        jButton3.setMaximumSize(new java.awt.Dimension(1280, 720));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoesActionPerformed(evt);
            }
        });

        jButton6.setText("Excluir");
        jButton6.setToolTipText("Remover perfil do banco de dados");
        jButton6.setMaximumSize(new java.awt.Dimension(1280, 720));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoesActionPerformed(evt);
            }
        });

        jButton7.setText("Alterar");
        jButton7.setToolTipText("Alterar perfil no banco de dados");
        jButton7.setMaximumSize(new java.awt.Dimension(1280, 720));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoesActionPerformed(evt);
            }
        });

        jButton8.setText("Limpar");
        jButton8.setToolTipText("Limpar campos");
        jButton8.setMaximumSize(new java.awt.Dimension(1280, 720));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paiseesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paiseesComboBoxActionPerformed
        // TODO add your handling code here:
        String pais = jComboBox4.getSelectedItem().toString();
        listaEstados(pais);
    }//GEN-LAST:event_paiseesComboBoxActionPerformed

    private void estadosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadosComboBoxActionPerformed
        // TODO add your handling code here:
         String estado = jComboBox5.getSelectedItem().toString();
         listaCidades(estado);
    }//GEN-LAST:event_estadosComboBoxActionPerformed

    private void botoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoesActionPerformed
        // TODO add your handling code here:
        String op = ((JButton)evt.getSource()).getText();
        switch(op){
            case "Pesquisar":
                exibeUser();
            break;
            case "Inserir":
                inserirUser();
            break;
            case "Excluir":
                removerUser();
            break;
            case "Alterar":
                 alterarUser();
            break;
            case "Limpar":
                 limparCampos();
            break;
             case "Buscar":
                 exibePerfisCompativeis();
            break;
        
        }
    }//GEN-LAST:event_botoesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        salvarInformacoes();//Executa a função de salvar as informações quando o JFrame é encerrado
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }
    public void inserirUser(){
        
        //Verifica se as informações preenchidas satisfazem os requisitos
        if(jTextField1.getText() != "" && this.dates.searchUser(jTextField1.getText()) == null && jTextField2.getText() != "" && jTextField4.getText() != "" && defineHobbies().size() > 3){
            this.dates.getListaDeUsuarios().add(geraUser());//Envia os dados para serem inceridos na lista de usuarios
            JOptionPane.showMessageDialog(this, "Dados Cadastrados com Sucesso.", "Cadastro efetuado!", JOptionPane.CLOSED_OPTION);
        }else{
            JOptionPane.showMessageDialog(this, "Possiveis problemas:\n-Algum campo está vazio.\n-Você selecionou menos 4 Hobbies.\n-A ID já existe no nosso sistema (Por favor, reinicie o programa e não altere o valor padrão).", "Cadastro não efetuado!", JOptionPane.ERROR_MESSAGE);
        }
    }
    public void removerUser(){
        if(this.dates.removerUser(geraUser()) == true){//Verifica se foi possivel remover o usuario e exibe mensagem conforme o retorno
            JOptionPane.showMessageDialog(this, "Usuário removido com sucesso.", "Usuário removido!", JOptionPane.CLOSED_OPTION);
        }else{
            JOptionPane.showMessageDialog(this, "O usuário não pode ser removido.", "Usuário não removido!", JOptionPane.ERROR_MESSAGE);
        }          
    }
    public void alterarUser(){
        if(this.dates.alterarUser(geraUser()) == true){
            JOptionPane.showMessageDialog(this, "Informações alteradas com sucesso.", "Informações alteradas!", JOptionPane.CLOSED_OPTION);
        }else{
            JOptionPane.showMessageDialog(this, "Informações não puderam ser alteradas.", "Informações não alteradas!", JOptionPane.ERROR_MESSAGE);
        } 
    }
    public void limparCampos(){
        
        jTextArea1.setText("");
        jTextField2.setText(this.usuarioDefalt.getNome());
        jTextField4.setText(this.usuarioDefalt.getTelefone());
        jComboBox1.getModel().setSelectedItem(this.usuarioDefalt.getSexo());
        jComboBox2.getModel().setSelectedItem(this.usuarioDefalt.getSexoDePreferencia());
        jComboBox3.getModel().setSelectedItem(this.usuarioDefalt.getEscolaridade());
        jComboBox4.getModel().setSelectedItem(this.usuarioDefalt.getLocalizacao().getPais());
        jComboBox5.getModel().setSelectedItem(this.usuarioDefalt.getLocalizacao().getEstado());
        jComboBox6.getModel().setSelectedItem(this.usuarioDefalt.getLocalizacao().getCidade());
        jComboBox7.getModel().setSelectedItem(this.usuarioDefalt.getIdade());
            
        this.proximidades[0].setSelected(true);
                
            
        for(int i = 0; i < this.hobbies.length; i++){
            this.hobbies[i].setSelected(false);
        }
        
        geraID();
    }
    public void salvarInformacoes(){
        this.dates.saveUserDB();
    }
    public Person geraUser(){//Gera um objeto Person e retorna para os metodos que precisam
        String id= jTextField1.getText();
        String nome = jTextField2.getText();
        String idade = jComboBox7.getSelectedItem().toString();
        String sexo = jComboBox1.getSelectedItem().toString();
        String telefone = jTextField4.getText();
        String sexoDePreferencia = jComboBox2.getSelectedItem().toString();
        String escolaridade = jComboBox3.getSelectedItem().toString();
       
        Address localizacao = new Address(jComboBox6.getSelectedItem().toString(), jComboBox5.getSelectedItem().toString(), jComboBox4.getSelectedItem().toString(), defineProximidade());
       
        Person user = new Person(id, nome, idade, sexo, telefone, sexoDePreferencia, defineHobbies(), escolaridade, localizacao);
       
        return user;
    }
    public void exibePerfisCompativeis(){//Mostra dentro da Area de Texto as informações de perfis compativeis ou exibe mensagem caso não encontre nehum perfil
        ArrayList<Person> compativeis = this.dates.searchMatch(geraUser());
        if(compativeis.size() > 0){
            jTextArea1.setText("");
            for(int j = 0;j < compativeis.size(); j++){
                jTextArea1.append("\n" + compativeis.get(j).getNome() + "\nIdade: " + compativeis.get(j).getIdade() + "    Sexualidade: " + compativeis.get(j).getSexo() + "    Escolaridade: "+ compativeis.get(j).getEscolaridade() + "    Telefone: " + compativeis.get(j).getTelefone() + "\nLocalização: " + compativeis.get(j).getLocalizacao().getCidade() + " - " + compativeis.get(j).getLocalizacao().getEstado() + "\n---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Nenhum perfil compativel encontrado.", "Desculpe!", JOptionPane.ERROR_MESSAGE);
        }
    }
    public void exibeUser(){//Busca as informações do usuario ao qual o ID pertence e exibe
        Person user = this.dates.searchUser(jTextField1.getText());
        
        if(user != null){
            jTextArea1.setText("");
            jTextField2.setText(user.getNome());
            jTextField4.setText(user.getTelefone());
            jComboBox1.getModel().setSelectedItem(user.getSexo());
            jComboBox2.getModel().setSelectedItem(user.getSexoDePreferencia());
            jComboBox3.getModel().setSelectedItem(user.getEscolaridade());
            jComboBox4.getModel().setSelectedItem(user.getLocalizacao().getPais());
            jComboBox5.getModel().setSelectedItem(user.getLocalizacao().getEstado());
            jComboBox6.getModel().setSelectedItem(user.getLocalizacao().getCidade());
            jComboBox7.getModel().setSelectedItem(user.getIdade());
            
            for(int i = 0; i < this.proximidades.length; i++){
                if(this.proximidades[i].getText().contains(user.getLocalizacao().getProximidade())){
                    this.proximidades[i].setSelected(true);
                }
            }
            
            for(int i = 0; i < this.hobbies.length; i++){
                this.hobbies[i].setSelected(false);
                for(int j = 0; j < user.getHobbies().size(); j++){
                    if(this.hobbies[i].getText().equals(user.getHobbies().get(j))){
                        this.hobbies[i].setSelected(true);
                    }
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "As informações não foram encontradas", "Desculpe!", JOptionPane.ERROR_MESSAGE);
        }
    }
    public ArrayList<String> defineHobbies(){//Verifica os campos CheckBox e adiciona o texto das que estão selecionadas e retorna como ArrayList 
        ArrayList<String> listaHobbies = new ArrayList<>();
        
        for(int i = 0; i < this.hobbies.length; i++){
            if(this.hobbies[i].isSelected()){
                listaHobbies.add(this.hobbies[i].getText());
            }  
        }
        
        return listaHobbies;
    }
    public String defineProximidade(){//Verifica o RadioButton selecionado e retorna seu texto;
        String proximidade = "";
        for(int i = 0; i < this.proximidades.length; i++){
            if(this.proximidades[i].isSelected()){
                proximidade = this.proximidades[i].getText();
            }
        }
        return proximidade;
    }
    public void geraID(){//Gera de Forma automatica uma ID unica;
        String id;
        Random rand = new Random();
        char[] letras = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".toCharArray();
        
        if(this.dates.getListaDeUsuarios().size() < 10){
            id = "GMDP" + rand.nextInt(99) + letras[rand.nextInt(letras.length)] + letras[rand.nextInt(letras.length)] + "0" + (this.dates.getListaDeUsuarios().size()+1);
        }else{
            id = "GMDP" + rand.nextInt(99) + letras[rand.nextInt(letras.length)] + letras[rand.nextInt(letras.length)] + (this.dates.getListaDeUsuarios().size()+1);
        }
        for(int i = 0; i < this.dates.getListaDeUsuarios().size(); i++){
            if(this.dates.getListaDeUsuarios().get(i).getId() == id){
                geraID();
             }
        }
        
        jTextField1.setText(id);
    }
    public void mensagensDeInicio(){
        JOptionPane.showMessageDialog(this, "Por Favor,\n\nPara o bom funcionamento do algoritmo\nsiga as seguintes regras:\n- Guarde bem sua ID ao cadastrar um novo usuário.\n  Você precisará dela para buscar suas informações.\n- Só altere o ID para fazer busca de informações\n  de um usuário já existente.\n- Marque pelo menos 4 opções do hobbies.\n- Preencha as informações corretamente.\n  Evite nomes e telefones falsos.\n- O salvamento é automatico, novas informaões\n  são guardadas ao encerrar o programa.", "Bem Vindo!", JOptionPane.INFORMATION_MESSAGE);
    }
   //------------------------------------------------------------------\\  
    /*Listas ComboBox, Check Box e RadioButton*/
    public void initListas(){
        listaSexualidade();
        listaPreferencia();
        listaEscolaridade();
        listaFaixa();
        listaPaises();
        addHobbies();
        addProximidade();
        geraID();
        mensagensDeInicio();
        
        //Usuario com campos padrões
        this.usuarioDefalt = geraUser();//Usado para retornar os campos para o valor padrão
    }
    
    public void listaSexualidade(){
        jComboBox1.addItem("Heterossexual - H");
        jComboBox1.addItem("Heterossexual - M");
        jComboBox1.addItem("Gay");
        jComboBox1.addItem("Lesbica");
        jComboBox1.addItem("Bissexual - H");
        jComboBox1.addItem("Bissexual - M");
        jComboBox1.addItem("Trans - H");
        jComboBox1.addItem("Trans - M");
    }
    public void listaPreferencia(){
        jComboBox2.addItem("Homem");
        jComboBox2.addItem("Mulher");
        jComboBox2.addItem("Ambos");
    }
    public void listaEscolaridade(){
        jComboBox3.addItem("Ensino Fundamental Incompleto");
        jComboBox3.addItem("Ensino Fundamental Completo");
        jComboBox3.addItem("Ensino Médio Incompleto");
        jComboBox3.addItem("Ensino Médio Completo");
        jComboBox3.addItem("Ensino Superior Incompleto");
        jComboBox3.addItem("Ensino Superior Completo");
    }
    public void listaFaixa(){
        jComboBox7.addItem("18-25");
        jComboBox7.addItem("26-33");
        jComboBox7.addItem("34-41");
        jComboBox7.addItem("42-49");
        jComboBox7.addItem("50-57");
        jComboBox7.addItem("58-65");
        jComboBox7.addItem("66-73");
        jComboBox7.addItem("74-81");
        jComboBox7.addItem("82-89");
        jComboBox7.addItem("90-97");
        jComboBox7.addItem("98-105");
    }
    public void listaPaises(){
        jComboBox4.addItem("Brasil");
    }
    public void listaEstados(String pais){
        switch(pais){
            case "Brasil":
                jComboBox5.removeAllItems();
                jComboBox5.addItem("AC");
                jComboBox5.addItem("AL");
                jComboBox5.addItem("AP");
                jComboBox5.addItem("AM");
                jComboBox5.addItem("BA");
                jComboBox5.addItem("CE");
                jComboBox5.addItem("ES");
                jComboBox5.addItem("GO");
                jComboBox5.addItem("MA");
                jComboBox5.addItem("MT");
                jComboBox5.addItem("MS");
                jComboBox5.addItem("MG");
                jComboBox5.addItem("PA");
                jComboBox5.addItem("PB");
                jComboBox5.addItem("PR");
                jComboBox5.addItem("PE");
                jComboBox5.addItem("PI");
                jComboBox5.addItem("RJ");
                jComboBox5.addItem("RN");
                jComboBox5.addItem("RS");
                jComboBox5.addItem("RO");
                jComboBox5.addItem("RR");
                jComboBox5.addItem("SC");
                jComboBox5.addItem("SP");
                jComboBox5.addItem("SE");
                jComboBox5.addItem("TO");
                jComboBox5.addItem("DF");
            break;
        }
    }
    public void listaCidades(String estado){
         switch(estado){
            case "AC":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Rio Branco");
                jComboBox6.addItem("Bujari");
                jComboBox6.addItem("Capixaba");
                jComboBox6.addItem("Porto Acre");
                jComboBox6.addItem("Senador Guiomard");
                jComboBox6.addItem("Sena Madureira");
                jComboBox6.addItem("Xapuri");
            break;
            case "AL":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Maceió");
                jComboBox6.addItem("Atalaia");
                jComboBox6.addItem("Barra de Santo Antônio");
                jComboBox6.addItem("Barra de São Miguel");
                jComboBox6.addItem("Coqueiro Seco");
                jComboBox6.addItem("Marechal Deodoro");
                jComboBox6.addItem("Messias");
                jComboBox6.addItem("Murici");
                jComboBox6.addItem("Paripueira");
                jComboBox6.addItem("Pilar");
                jComboBox6.addItem("Rio Largo");
                jComboBox6.addItem("Santa Luzia do Norte");
                jComboBox6.addItem("Satuba");
            break;
            case "AP":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Macapá");
                jComboBox6.addItem("Santana");
                jComboBox6.addItem("Mazagão");
            break;
            case "AM":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Manaus");
                jComboBox6.addItem("Careiro da Várzea");
                jComboBox6.addItem("Iranduba");
                jComboBox6.addItem("Itacoatiara");
                jComboBox6.addItem("Novo Airão");
                jComboBox6.addItem("Presidente Figueiredo");
                jComboBox6.addItem("Rio Preto da Eva");  
            break;
            case "BA":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Salvador");
                jComboBox6.addItem("Camaçari");
                jComboBox6.addItem("Candeias");
                jComboBox6.addItem("Dias d'Ávila");
                jComboBox6.addItem("Itaparica");
                jComboBox6.addItem("Lauro de Freitas");
                jComboBox6.addItem("Madre de Deus");
                jComboBox6.addItem("Mata de São João");
                jComboBox6.addItem("Pojuca");
                jComboBox6.addItem("Salvador");
                jComboBox6.addItem("São Francisco do Conde");
                jComboBox6.addItem("São Sebastião do Passé");
                jComboBox6.addItem("Simões Filho");
                jComboBox6.addItem("Vera Cruz");
            break;
            case "CE":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Fortaleza");
                jComboBox6.addItem("Aquiraz");
                jComboBox6.addItem("Caucaia");
                jComboBox6.addItem("Maracanaú");
                jComboBox6.addItem("Maranguape");
                jComboBox6.addItem("Pacatuba");
            break;
            case "ES":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Vitória");
                jComboBox6.addItem("Vila Velha");
                jComboBox6.addItem("Serra");
                jComboBox6.addItem("Cariacica");
                jComboBox6.addItem("Viana");
                jComboBox6.addItem("Guarapari");
                jComboBox6.addItem("Fundão");
            break;
            case "GO":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Goiânia");
                jComboBox6.addItem("Abadia de Goiás");
                jComboBox6.addItem("Aparecida de Goiânia");
                jComboBox6.addItem("Aragoiânia");
                jComboBox6.addItem("Bela Vista de Goiás");
                jComboBox6.addItem("Bonfinópolis");
                jComboBox6.addItem("Brazabrantes");
                jComboBox6.addItem("Caldazinha");
                jComboBox6.addItem("Caturaí");
                jComboBox6.addItem("Goianápolis");
                jComboBox6.addItem("Goianira");
                jComboBox6.addItem("Guapó");
                jComboBox6.addItem("Hidrolândia");
                jComboBox6.addItem("Inhumas");
                jComboBox6.addItem("Nerópolis");
                jComboBox6.addItem("Nova Veneza");
                jComboBox6.addItem("Santa Bárbara de Goiás");
                jComboBox6.addItem("Santo Antônio de Goiás");
                jComboBox6.addItem("Senador Canedo");
                jComboBox6.addItem("Terezópolis de Goiás");
                jComboBox6.addItem("Trindade");      
            break;
            case "MA":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("São Luís");
                jComboBox6.addItem("Alcântara");
                jComboBox6.addItem("Bacabeira");
                jComboBox6.addItem("Icatu");
                jComboBox6.addItem("Paço do Lumiar");
                jComboBox6.addItem("Raposa");
                jComboBox6.addItem("Rosário");
                jComboBox6.addItem("Santa Rita");
                jComboBox6.addItem("São José de Ribamar");
            break;
            case "MT":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Cuiabá");
                jComboBox6.addItem("Várzea Grande");
                jComboBox6.addItem("Santo Antônio de Leverger");
                jComboBox6.addItem("Nossa Senhora do Livramento");
            break;
            case "MS":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Campo Grande");
                jComboBox6.addItem("Bandeirantes");
                jComboBox6.addItem("Camapuã");
                jComboBox6.addItem("Corguinho");
                jComboBox6.addItem("Dois Irmãos do Buriti");
                jComboBox6.addItem("Jaraguari");
                jComboBox6.addItem("Nova Alvorada do Sul");
                jComboBox6.addItem("Ribas do Rio Pardo");
                jComboBox6.addItem("Rio Negro");
                jComboBox6.addItem("Rochedo");
                jComboBox6.addItem("São Gabriel do Oeste");
                jComboBox6.addItem("Sidrolândia");
                jComboBox6.addItem("Terenos");
            break;
            case "MG":
               jComboBox6.removeAllItems();
               jComboBox6.addItem("Belo Horizonte");
               jComboBox6.addItem("Betim");
               jComboBox6.addItem("Contagem");
               jComboBox6.addItem("Ibirité");
               jComboBox6.addItem("Lagoa Santa");
               jComboBox6.addItem("Nova Lima");
               jComboBox6.addItem("Pedro Leopoldo");
               jComboBox6.addItem("Raposos");
               jComboBox6.addItem("Ribeirão das Neves");
               jComboBox6.addItem("Rio Acima");
               jComboBox6.addItem("Sabará");
               jComboBox6.addItem("Santa Luzia");
               jComboBox6.addItem("Vespasiano");
            break;
            case "PA":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Belém");
                jComboBox6.addItem("Ananindeua");
                jComboBox6.addItem("Benevides");
                jComboBox6.addItem("Marituba");        
                jComboBox6.addItem("Santa Bárbara");
            break;
            case "PB":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("João Pessoa");
                jComboBox6.addItem("Alhandra");
                jComboBox6.addItem("Bayeux");
                jComboBox6.addItem("Caaporã");
                jComboBox6.addItem("Cabedelo");
                jComboBox6.addItem("Conde");
                jComboBox6.addItem("Cruz do Espírito Santo");
                jComboBox6.addItem("Lucena");
                jComboBox6.addItem("Pedras de Fogo");
                jComboBox6.addItem("Pitimbu");
                jComboBox6.addItem("Rio Tinto");
                jComboBox6.addItem("Santa Rita");
            break;
            case "PR":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Curitiba");
                jComboBox6.addItem("Almirante");
                jComboBox6.addItem("Tamandaré");
                jComboBox6.addItem("Araucária");
                jComboBox6.addItem("Campina Grande do Sul");
                jComboBox6.addItem("Campo Largo");
                jComboBox6.addItem("Campo Magro");
                jComboBox6.addItem("Colombo");
                jComboBox6.addItem("Fazenda Rio Grande");
                jComboBox6.addItem("Itaperuçu");
                jComboBox6.addItem("Pinhais");
                jComboBox6.addItem("Piraquara");
                jComboBox6.addItem("Quatro Barras");
                jComboBox6.addItem("Rio Branco do Sul");
                jComboBox6.addItem("São José dos Pinhais");
                jComboBox6.addItem("Adrianópolis");
                jComboBox6.addItem("Bocaiúva do Sul");
                jComboBox6.addItem("Cerro Azul");
                jComboBox6.addItem("Doutor Ulysses");
                jComboBox6.addItem("Itaperuçu");
                jComboBox6.addItem("Rio Branco do Sul");
                jComboBox6.addItem("Tunas do Paraná");
            break;
            case "PE":
                jComboBox6.removeAllItems();
                 jComboBox6.addItem("Recife");
                 jComboBox6.addItem("Araçoiaba");
                 jComboBox6.addItem("Igarassu");
                 jComboBox6.addItem("Itapissuma");
                 jComboBox6.addItem("Ilha de Itamaracá");
                 jComboBox6.addItem("Abreu e Lima");
                 jComboBox6.addItem("Paulista");
                 jComboBox6.addItem("Olinda");
                 jComboBox6.addItem("Camaragibe");
                 jComboBox6.addItem("Jaboatão dos Guararapes");
                 jComboBox6.addItem("São Lourenço da Mata");
                 jComboBox6.addItem("Moreno");
                 jComboBox6.addItem("Cabo de Santo Agostinho");
                 jComboBox6.addItem("Ipojuca");
            break;
            case "PI":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Teresina");
                jComboBox6.addItem("Altos");
                jComboBox6.addItem("Beneditinos");
                jComboBox6.addItem("Coivaras");
                jComboBox6.addItem("Curralinhos");
                jComboBox6.addItem("Demerval Lobão");
                jComboBox6.addItem("José de Freitas");
                jComboBox6.addItem("Lagoa Alegre");
                jComboBox6.addItem("Lagoa do Piauí");
                jComboBox6.addItem("Miguel Leão");
                jComboBox6.addItem("Monsenhor Gil");
                jComboBox6.addItem("Nazária");
                jComboBox6.addItem("Pau D'Arco do Piauí");
                jComboBox6.addItem("União");
                jComboBox6.addItem("Timon");
            break;
            case "RJ":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Rio de Janeiro");
                jComboBox6.addItem("Duque de Caxias");
                jComboBox6.addItem("Itaboraí");
                jComboBox6.addItem("Itaguaí");
                jComboBox6.addItem("Magé");
                jComboBox6.addItem("Mangaratiba");
                jComboBox6.addItem("Maricá");
                jComboBox6.addItem("Nilópolis");
                jComboBox6.addItem("Niterói");
                jComboBox6.addItem("Nova Iguaçu");
                jComboBox6.addItem("Paracambi");
                jComboBox6.addItem("Petrópolis");
                jComboBox6.addItem("São Gonçalo");
                jComboBox6.addItem("São João de Meriti"); 
            break;
            case "RN":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Natal"); 
                jComboBox6.addItem("Parnamirim"); 
                jComboBox6.addItem("Macaíba"); 
                jComboBox6.addItem("São Gonçalo do Amarante"); 
                jComboBox6.addItem("Extremoz"); 
                jComboBox6.addItem("Ceará-Mirim"); 
                jComboBox6.addItem("São José de Mipibu"); 
                jComboBox6.addItem("Nísia Floresta"); 
                jComboBox6.addItem("Monte Alegre"); 
                jComboBox6.addItem("Vera Cruz"); 
                jComboBox6.addItem("Maxaranguape"); 
                jComboBox6.addItem("Ielmo Marinho"); 
                jComboBox6.addItem("Arês"); 
                jComboBox6.addItem("Goianinha"); 
                jComboBox6.addItem("Bom Jesus"); 
            break;
            case "RS":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Porto Alegre");
                jComboBox6.addItem("Alvorada");
                jComboBox6.addItem("Cachoeirinha");
                jComboBox6.addItem("Canoas");
                jComboBox6.addItem("Esteio");
                jComboBox6.addItem("Glorinha");
                jComboBox6.addItem("Gravataí");
                jComboBox6.addItem("Nova Santa Rita");
                jComboBox6.addItem("Sapucaia do Sul");
                jComboBox6.addItem("Viamão");               
            break;
            case "RO":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Porto Velho");
                jComboBox6.addItem("Candeias do Jamari");
               
            break;
            case "RR":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Boa Vista");
                jComboBox6.addItem("Alto Alegre");
                jComboBox6.addItem("Bonfim");
                jComboBox6.addItem("Bonfim");
                jComboBox6.addItem("Mucajaí");
               
            break;
            case "SC":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Florianópolis");
                jComboBox6.addItem("São José");
                jComboBox6.addItem("Palhoça");
                jComboBox6.addItem("Biguaçu");
                jComboBox6.addItem("Santo Amaro da Imperatriz");
                jComboBox6.addItem("Governador Celso Ramos");
                jComboBox6.addItem("Antônio Carlos");
                jComboBox6.addItem("Águas Mornas");
                jComboBox6.addItem("São Pedro de Alcântara");
            break;
            case "SP":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("São Paulo");
                jComboBox6.addItem("Arujá");
                jComboBox6.addItem("Barueri");
                jComboBox6.addItem("Biritiba Mirim");
                jComboBox6.addItem("Caieiras");
                jComboBox6.addItem("Cajamar");
                jComboBox6.addItem("Carapicuíba");
                jComboBox6.addItem("Cotia");
                jComboBox6.addItem("Diadema");
                jComboBox6.addItem("Embu");
                jComboBox6.addItem("Embu-Guaçu");
                jComboBox6.addItem("Ferraz de Vasconcelos");
                jComboBox6.addItem("Francisco Morato");
                jComboBox6.addItem("Franco da Rocha");
                jComboBox6.addItem("Guararema");
                jComboBox6.addItem("Guarulhos");
                jComboBox6.addItem("Itapecerica da Serra");
                jComboBox6.addItem("Itapevi");
                jComboBox6.addItem("Itaquaquecetuba");
                jComboBox6.addItem("Jandira");
                jComboBox6.addItem("Juquitiba");
                jComboBox6.addItem("Mairiporã");
                jComboBox6.addItem("Mauá");
                jComboBox6.addItem("Mogi das Cruzes");
                jComboBox6.addItem("Osasco");
                jComboBox6.addItem("Pirapora do Bom Jesus");
                jComboBox6.addItem("Poá");
                jComboBox6.addItem("Ribeirão Pires");
                jComboBox6.addItem("Rio Grande da Serra");
                jComboBox6.addItem("Salesópolis");
                jComboBox6.addItem("Santa Isabel");
                jComboBox6.addItem("Santana do Parnaíba");
                jComboBox6.addItem("Santo André");
                jComboBox6.addItem("São Bernardo do Campo");
                jComboBox6.addItem("São Caetano do Sul");
                jComboBox6.addItem("São Lourenço da Serra Suzano");
                jComboBox6.addItem("Suzano");
                jComboBox6.addItem("Taboão da Serra");
                jComboBox6.addItem("Vargem Grande Paulista");
            break;
            case "SE":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Aracaju");
                jComboBox6.addItem("Barra dos Coqueiros");
                jComboBox6.addItem("Nossa Senhora do Socorro");
                jComboBox6.addItem("São Cristóvão");
               
            break;
            case "TO":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Palmas");
                jComboBox6.addItem("Aparecida do Rio Negro");
                jComboBox6.addItem("Barrolândia");
                jComboBox6.addItem("Brejinho de Nazaré");
                jComboBox6.addItem("Fátima");
                jComboBox6.addItem("Ipueiras");
                jComboBox6.addItem("Lajeado");
                jComboBox6.addItem("Miracema do Tocantins");
                jComboBox6.addItem("Miranorte");
                jComboBox6.addItem("Monte do Carmo");
                jComboBox6.addItem("Oliveira de Fátima");
                jComboBox6.addItem("Paraíso do Tocantins");
                jComboBox6.addItem("Porto Nacional");
                jComboBox6.addItem("Pugmil");
                jComboBox6.addItem("Silvanópolis");
                jComboBox6.addItem("Tocantínia");
            break;
            case "DF":
                jComboBox6.removeAllItems();
                jComboBox6.addItem("Brasília");
                jComboBox6.addItem("Ceilândia");
                jComboBox6.addItem("Gama");
                jComboBox6.addItem("Taguatinga");
                jComboBox6.addItem("Planaltina");
                jComboBox6.addItem("Sobradinho");
            break;
            
        }
    }
    public void addHobbies(){
        this.hobbies = new JCheckBox[21];
        
        this.hobbies[0] = this.jCheckBox1;
        this.hobbies[1] = this.jCheckBox2;
        this.hobbies[2] = this.jCheckBox3;
        this.hobbies[3] = this.jCheckBox4;
        this.hobbies[4] = this.jCheckBox5;
        this.hobbies[5] = this.jCheckBox6;
        this.hobbies[6] = this.jCheckBox7;
        this.hobbies[7] = this.jCheckBox8;
        this.hobbies[8] = this.jCheckBox9;
        this.hobbies[9] = this.jCheckBox10;
        this.hobbies[10] = this.jCheckBox11;
        this.hobbies[11] = this.jCheckBox12;
        this.hobbies[12] = this.jCheckBox13;
        this.hobbies[13] = this.jCheckBox14;
        this.hobbies[14] = this.jCheckBox15;
        this.hobbies[15] = this.jCheckBox16;
        this.hobbies[16] = this.jCheckBox17;
        this.hobbies[17] = this.jCheckBox18;
        this.hobbies[18] = this.jCheckBox19;
        this.hobbies[19] = this.jCheckBox20;
        this.hobbies[20] = this.jCheckBox21;
    }
    public void addProximidade(){
        this.proximidades = new JRadioButton[4];
        
        this.proximidades[0] = jRadioButton1;
        this.proximidades[1] = jRadioButton2;
        this.proximidades[2] = jRadioButton3;
        this.proximidades[3] = jRadioButton4;
        
        this.proximidades[0].setSelected(true);
    }
   //------------------------------------------------------------------\\ 
    
    private GetMeADate dates;
    private JCheckBox[] hobbies;
    private JRadioButton[] proximidades;
    private Person usuarioDefalt;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.ButtonGroup proximidadeGroup;
    // End of variables declaration//GEN-END:variables
}
